name: 'broken-link-check'
description: 'Find broken links, missing images, etc within your HTML.'
author: 'Cian Leow'
branding: 
  icon: 'anchor'
  color: 'purple'
inputs:
  url:  # id of input
    description: 'Url of site'
    required: true
  honorRobotExclusions:
    description: 'Overwrite standard skipping rel=nofollow links'
    required: false
    default: true
  ignorePatterns: 
    description: 'Ignore urls based on patterns'
    required: false
    default: ''
  recursiveLinks: 
    description: 'Walk through the whole website and check all the urls'
    required: false
    default: false
outputs:
  result: # id of output
    description: 'Report of links'
runs:
  using: 'composite'
  steps: 
    - name: Install blc
      run: sudo npm install -g broken-link-checker
      shell: bash

    - name: Run script
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.url }} ${{ inputs.honorRobotExclusions }} ${{ inputs.ignorePatterns }} ${{ inputs.recursiveLinks }}
      shell: bash
